### ISSUE TITLE
User activity log 

### ISSUE THREAD

**Issue by iamiddy** [Dproz/dproz-servicing-service#14]
Track user activities, generate logs suitable for amazing Dashboard

1.  Registered users by Days, Hours , Week, Months etc
2. Verified accounts after registration
3. Logged in users 
4. Returning users

**Comment by prabhakar349** [comment]
@iamiddy  do you think for now use a generic ApplicationEventListener to listen to all application events will suffice.  ?  The listener for now will log the event?

**Comment by iamiddy** [comment]
Good question @prabhakar349 . What are the alternatives?

**Comment by prabhakar349** [comment]
Other alternatives 

1) Create a AduitEvent service, and call the service at all places to perform of the auditing of event

2) Some Aspect which can be triggered on certain methods to perform the auditing of event logs

**Comment by iamiddy** [comment]
@prabhakar349 what option are you learning to?

**Comment by prabhakar349** [comment]
May be  this to start with 

"Create a AduitEvent service, and call the service at all places to perform of the auditing of event" and then move towards aspect

**Comment by prabhakar349** [comment]
closing this as MVP solution is implemented
